# Generated by Django 5.2.17 on 2026-10-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_upgradestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='favicon_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationBrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon')], max_length=20)),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(max_length=50)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_images', to='core.organization')),
            ],
            options={
                'db_table': 'organization_brand_images',
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind'), name='unique_brand_image_per_kind')],
            },
        ),
    ]
