# Generated by Django 5.2.17 on 2026-10-06 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_password_reset_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'permissions': [('can_manage_billing', 'Can manage billing and subscription'), ('can_delete_organization', 'Can delete organization'), ('can_manage_owners', 'Can add and remove owners'), ('can_view_audit_log', 'Can view the audit log'), ('can_invite_members', 'Can invite team members'), ('can_manage_organization', 'Can manage organization settings'), ('can_manage_cycles', 'Can create and run review cycles for others'), ('can_view_all_reports', 'Can view all organization reports'), ('can_investigate_responses', 'Can view reviewer identities for investigations')]},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_create_cycles_for_others',
            field=models.BooleanField(default=False, help_text='Mirrors the Cycle Manager role (kept in sync by accounts.permissions.set_user_roles)'),
        ),
        migrations.CreateModel(
            name='EmailMFACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_mfa_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
