# Generated by Django 5.2.18 on 2026-10-07 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mfa_trusted_device'),
        ('core', '0011_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='report_all_campuses',
            field=models.BooleanField(default=True, help_text='Report Viewers: may read reports for every reviewee, including reviewees with no campus and campuses added later'),
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='core.organization')),
            ],
            options={
                'verbose_name_plural': 'campuses',
                'db_table': 'campuses',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='reviewee',
            name='campuses',
            field=models.ManyToManyField(blank=True, help_text='Report Viewers limited to campuses only see reports for reviewees in one of their campuses', related_name='reviewees', to='accounts.campus'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='report_campuses',
            field=models.ManyToManyField(blank=True, help_text='Report Viewers without "all campuses": the campuses whose reviewees\' reports they may read', related_name='report_viewers', to='accounts.campus'),
        ),
    ]
