# Generated by Django 5.2.18 on 2026-10-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_campuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvitation",
            name="report_all_campuses",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="report_campuses",
            field=models.ManyToManyField(
                blank=True, related_name="pending_invitations", to="accounts.campus"
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="roles",
            field=models.JSONField(
                blank=True,
                help_text='Role keys granted on acceptance, e.g. ["org_admin", "report_viewer"]',
                null=True,
            ),
        ),
    ]
